/**
 * OMP Provider Presets
 *
 * 预设按认证方式分两组（与 omp 的实际能力对齐）：
 * - OAuth：omp 凭据库支持登录的供应商，无需填 baseUrl / apiKey / 模型
 * - API Key：其余全部（官方 API、聚合站、中转站、本地推理），走 baseUrl + apiKey
 *
 * 注意：OAuth 预设的 oauthProviderId 必须与 `omp auth-broker list --json`
 * 返回的真实 id 完全一致，否则查不到登录态。
 */

import type { OmpProviderPreset } from "@/types/omp";

// ────────────────────────────────────────────────────────────────────────────
// OAUTH - omp OAuth 登录供应商
// 分类依据（唯一权威）：omp 源码 packages/catalog/src/compat/rules/auth/<id>.kdl 的 login 字段
//   login = oauth-code / custom / device-code → OAuth（本组）
//   login = api-key 或无 login               → API Key 组
// 注意：`omp auth-broker list`（76 项）与 auth-broker login 的参数名都包含交互式 API-key
// 登录者，不能用于区分 OAuth/API Key；官方 providers.md 亦有滞后（以源码 kdl 为准）
// ────────────────────────────────────────────────────────────────────────────

export const SUBSCRIPTION_PRESETS: OmpProviderPreset[] = [
  {
    id: "anthropic",
    name: "Anthropic",
    type: "oauth",
    category: "subscription",
    description: "Claude models via OAuth authentication",
    websiteUrl: "https://www.anthropic.com",
    docsUrl: "https://docs.anthropic.com",
    icon: "anthropic",
    oauthProviderId: "anthropic",
    defaultApi: "anthropic-messages",
    defaultModels: [
      {
        id: "claude-3.7-sonnet",
        name: "Claude 3.7 Sonnet",
        api: "anthropic-messages",
        reasoning: true,
        contextWindow: 200000,
        maxTokens: 8192,
      },
      {
        id: "claude-opus-4-20250514",
        name: "Claude Opus 4",
        api: "anthropic-messages",
        reasoning: true,
        contextWindow: 200000,
        maxTokens: 16384,
      },
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    type: "oauth",
    category: "subscription",
    description: "GPT models via OAuth authentication",
    websiteUrl: "https://openai.com",
    docsUrl: "https://platform.openai.com/docs",
    icon: "openai",
    // 必须与 omp 凭据库 id 一致：`omp token openai-codex --list` 才是真实账号，
    // 写 "openai" 会永远查不到登录态（旧版本即因此显示「未登录」）。
    oauthProviderId: "openai-codex",
    defaultApi: "openai-responses",
    defaultModels: [
      {
        id: "gpt-4o",
        name: "GPT-4o",
        api: "openai-responses",
        reasoning: false,
        contextWindow: 128000,
        maxTokens: 16384,
      },
      {
        id: "o1",
        name: "o1",
        api: "openai-responses",
        reasoning: true,
        contextWindow: 200000,
        maxTokens: 100000,
      },
    ],
  },
  {
    id: "google",
    name: "Google AI",
    type: "oauth",
    category: "subscription",
    description: "Gemini models via OAuth authentication",
    websiteUrl: "https://ai.google.dev",
    docsUrl: "https://ai.google.dev/docs",
    icon: "google",
    oauthProviderId: "google-gemini-cli",
    defaultApi: "google-generative-ai",
    defaultModels: [
      {
        id: "gemini-2.0-flash-exp",
        name: "Gemini 2.0 Flash (Experimental)",
        api: "google-generative-ai",
        reasoning: false,
        contextWindow: 1000000,
        maxTokens: 8192,
      },
      {
        id: "gemini-2.0-flash-thinking-exp-01-21",
        name: "Gemini 2.0 Flash Thinking",
        api: "google-generative-ai",
        reasoning: true,
        contextWindow: 32768,
        maxTokens: 8192,
      },
    ],
  },
  {
    id: "xai",
    name: "xAI",
    type: "oauth",
    category: "subscription",
    description: "Grok models via OAuth authentication",
    websiteUrl: "https://x.ai",
    docsUrl: "https://docs.x.ai",
    icon: "xai",
    oauthProviderId: "xai-oauth",
    defaultApi: "openai-completions",
    defaultModels: [
      {
        id: "grok-2-latest",
        name: "Grok 2",
        api: "openai-completions",
        reasoning: false,
        contextWindow: 131072,
        maxTokens: 32768,
      },
    ],
  },
  // GitHub Copilot：omp 凭据库实测支持（浏览器/设备码登录）
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    type: "oauth",
    category: "subscription",
    description: "GitHub Copilot 订阅（浏览器登录）",
    websiteUrl: "https://github.com/features/copilot",
    docsUrl: "https://docs.github.com/copilot",
    icon: "githubcopilot",
    oauthProviderId: "github-copilot",
    defaultApi: "openai-completions",
  },
  // ── 以下 11 个为 omp 官方文档 providers.md 明确的 /login OAuth 供应商 ──
  // （oauthProviderId 必须与 omp 凭据库 id 完全一致）
  {
    id: "cursor",
    name: "Cursor",
    type: "oauth",
    category: "subscription",
    description: "Cursor 订阅（OAuth 登录）",
    icon: "cursor",
    websiteUrl: "https://cursor.com",
    docsUrl: "https://docs.cursor.com",
    oauthProviderId: "cursor",
    defaultApi: "openai-completions",
  },
  // 注：ollama-cloud / qwen-portal 的 omp auth policy 为 login="api-key"
  //（源码 rules/auth/*.kdl），已移入 API Key 组，不属 OAuth
  {
    id: "kimi-code",
    name: "Kimi Code",
    type: "oauth",
    category: "subscription",
    description: "Kimi Code（OAuth 登录）",
    websiteUrl: "https://platform.moonshot.cn",
    docsUrl: "https://platform.moonshot.cn/docs",
    icon: "kimi",
    oauthProviderId: "kimi-code",
    defaultApi: "openai-completions",
  },
  // 注：wafer-serverless 的 omp auth policy 为 login="api-key"（源码 kdl），已移入 API Key 组
  {
    id: "google-antigravity",
    name: "Google Antigravity",
    type: "oauth",
    category: "subscription",
    description: "Google Antigravity（OAuth 登录）",
    websiteUrl: "https://antigravity.google",
    icon: "google",
    oauthProviderId: "google-antigravity",
    defaultApi: "openai-completions",
  },
  {
    id: "devin",
    name: "Devin",
    type: "oauth",
    category: "subscription",
    description: "Devin（OAuth 登录）",
    icon: "devin",
    websiteUrl: "https://devin.ai",
    docsUrl: "https://docs.devin.ai",
    oauthProviderId: "devin",
    defaultApi: "openai-completions",
  },
  {
    id: "gitlab-duo",
    name: "GitLab Duo",
    type: "oauth",
    category: "subscription",
    description: "GitLab Duo（OAuth 登录）",
    icon: "gitlab",
    websiteUrl: "https://about.gitlab.com",
    docsUrl: "https://docs.gitlab.com/user/gitlab_duo",
    oauthProviderId: "gitlab-duo",
    defaultApi: "openai-completions",
  },
  {
    id: "gitlab-duo-agent",
    name: "GitLab Duo (Agent)",
    type: "oauth",
    category: "subscription",
    description: "GitLab Duo Agent（OAuth 登录）",
    icon: "gitlab",
    websiteUrl: "https://about.gitlab.com",
    docsUrl: "https://docs.gitlab.com/user/gitlab_duo",
    oauthProviderId: "gitlab-duo-agent",
    defaultApi: "openai-completions",
  },
  // 注：zai / zhipu-coding-plan 的 omp auth policy 为 login="api-key"（源码 kdl），
  // 已移入 API Key 组；真正走 OAuth 的是 zai-coding-plan（·Sign in）
  {
    id: "zai-coding-plan",
    name: "Z.AI（GLM Coding Plan · Sign in）",
    type: "oauth",
    category: "subscription",
    description: "Z.AI GLM Coding Plan（OAuth 登录）",
    websiteUrl: "https://z.ai",
    icon: "zhipu",
    oauthProviderId: "zai-coding-plan",
    defaultApi: "openai-completions",
  },
  // ── 以下 8 个依 omp 源码 rules/auth/*.kdl 的 login 字段补入 OAuth 组 ─
  {
    id: "kilo",
    name: "Kilo Code",
    type: "oauth",
    category: "subscription",
    description: "Kilo Gateway（OAuth 登录）",
    websiteUrl: "https://kilo.ai",
    icon: "kilocode",
    oauthProviderId: "kilo",
    defaultApi: "openai-completions",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    type: "oauth",
    category: "subscription",
    description: "Perplexity Pro/Max（OAuth 登录）",
    websiteUrl: "https://www.perplexity.ai",
    icon: "perplexity",
    oauthProviderId: "perplexity",
    defaultApi: "openai-completions",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    type: "oauth",
    category: "subscription",
    description: "OpenRouter（OAuth 登录）",
    websiteUrl: "https://openrouter.ai",
    icon: "openrouter",
    oauthProviderId: "openrouter",
    defaultApi: "openai-completions",
  },
  {
    id: "xiaomi",
    name: "Xiaomi MiMo",
    type: "oauth",
    category: "subscription",
    description: "小米 MiMo（OAuth 登录）",
    websiteUrl: "https://www.xiaomimimo.com",
    icon: "xiaomimimo",
    oauthProviderId: "xiaomi",
    defaultApi: "openai-completions",
  },
  {
    id: "alibaba-coding-plan",
    name: "Alibaba Coding Plan",
    type: "oauth",
    category: "subscription",
    description: "Alibaba Coding Plan（OAuth 登录）",
    websiteUrl: "https://coding.dashscope.com",
    icon: "alibaba",
    oauthProviderId: "alibaba-coding-plan",
    defaultApi: "openai-completions",
  },
  {
    id: "alibaba-token-plan",
    name: "QwenCloud Token Plan",
    type: "oauth",
    category: "subscription",
    description: "Alibaba Bailian Token Plan（OAuth 登录）",
    websiteUrl: "https://www.alibabacloud.com/help/model-studio",
    icon: "bailian",
    oauthProviderId: "alibaba-token-plan",
    defaultApi: "openai-completions",
  },
  {
    id: "cloudflare-ai-gateway",
    name: "Cloudflare AI Gateway",
    type: "oauth",
    category: "subscription",
    description: "Cloudflare AI Gateway（OAuth 登录）",
    websiteUrl: "https://developers.cloudflare.com/ai-gateway",
    icon: "cloudflare",
    oauthProviderId: "cloudflare-ai-gateway",
    defaultApi: "openai-completions",
  },
  {
    id: "muse-code",
    name: "Muse Code",
    type: "oauth",
    category: "subscription",
    description: "Muse Code 订阅（设备码登录）",
    websiteUrl: "https://www.meta.ai",
    icon: "meta",
    oauthProviderId: "muse-code",
    defaultApi: "openai-completions",
  },
];

// ────────────────────────────────────────────────────────────────────────────
// API (API Key) - 28 providers
// ────────────────────────────────────────────────────────────────────────────

export const API_PRESETS: OmpProviderPreset[] = [
  // Major providers (official APIs)
  {
    id: "anthropic",
    name: "Anthropic API",
    type: "api-key",
    category: "api",
    description: "Claude models via official API key",
    websiteUrl: "https://www.anthropic.com",
    docsUrl: "https://docs.anthropic.com",
    icon: "anthropic",
    defaultBaseUrl: "https://api.anthropic.com",
    defaultApi: "anthropic-messages",
    requiresApiKey: true,
    envKeyName: "ANTHROPIC_API_KEY",
  },
  {
    id: "openai",
    name: "OpenAI API",
    type: "api-key",
    category: "api",
    description: "GPT models via official API key",
    websiteUrl: "https://openai.com",
    docsUrl: "https://platform.openai.com/docs",
    icon: "openai",
    defaultBaseUrl: "https://api.openai.com/v1",
    defaultApi: "openai-responses",
    requiresApiKey: true,
    envKeyName: "OPENAI_API_KEY",
  },
  {
    id: "google",
    name: "Google AI API",
    type: "api-key",
    category: "api",
    description: "Gemini models via official API key",
    websiteUrl: "https://ai.google.dev",
    docsUrl: "https://ai.google.dev/docs",
    icon: "google",
    defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta",
    defaultApi: "google-generative-ai",
    requiresApiKey: true,
    envKeyName: "GOOGLE_API_KEY",
  },
  {
    id: "xai",
    name: "xAI API",
    type: "api-key",
    category: "api",
    description: "Grok models via official API key",
    websiteUrl: "https://x.ai",
    docsUrl: "https://docs.x.ai",
    icon: "xai",
    defaultBaseUrl: "https://api.x.ai/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "XAI_API_KEY",
  },
  {
    // id 对齐 omp 内置目录（models.db provider_id）：避免与内置 deepseek 并存成两个供应商
    id: "deepseek",
    name: "DeepSeek API",
    type: "api-key",
    category: "api",
    description: "DeepSeek models via official API key",
    websiteUrl: "https://www.deepseek.com",
    docsUrl: "https://api-docs.deepseek.com",
    icon: "deepseek",
    defaultBaseUrl: "https://api.deepseek.com",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "DEEPSEEK_API_KEY",
  },
  {
    id: "mistral",
    name: "Mistral AI API",
    type: "api-key",
    category: "api",
    description: "Mistral models via official API key",
    websiteUrl: "https://mistral.ai",
    docsUrl: "https://docs.mistral.ai",
    icon: "mistral",
    defaultBaseUrl: "https://api.mistral.ai/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "MISTRAL_API_KEY",
  },
  {
    id: "cohere-api",
    name: "Cohere API",
    type: "api-key",
    category: "api",
    description: "Command models via official API key",
    websiteUrl: "https://cohere.com",
    docsUrl: "https://docs.cohere.com",
    icon: "cohere",
    defaultBaseUrl: "https://api.cohere.ai/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "COHERE_API_KEY",
  },
  {
    id: "perplexity-api",
    name: "Perplexity API",
    type: "api-key",
    category: "api",
    description: "Perplexity models via official API key",
    websiteUrl: "https://www.perplexity.ai",
    docsUrl: "https://docs.perplexity.ai",
    icon: "perplexity",
    defaultBaseUrl: "https://api.perplexity.ai",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "PERPLEXITY_API_KEY",
  },
  {
    id: "together",
    name: "Together AI API",
    type: "api-key",
    category: "api",
    description: "Open source models via official API key",
    websiteUrl: "https://www.together.ai",
    docsUrl: "https://docs.together.ai",
    icon: "together",
    defaultBaseUrl: "https://api.together.xyz/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "TOGETHER_API_KEY",
  },
  {
    id: "fireworks-api",
    name: "Fireworks AI API",
    type: "api-key",
    category: "api",
    description: "Fast inference via official API key",
    websiteUrl: "https://fireworks.ai",
    docsUrl: "https://docs.fireworks.ai",
    icon: "fireworks",
    defaultBaseUrl: "https://api.fireworks.ai/inference/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "FIREWORKS_API_KEY",
  },
  // Chinese providers
  {
    id: "zhipu",
    name: "智谱AI (ZhipuAI)",
    type: "api-key",
    category: "api",
    description: "GLM models via official API key",
    websiteUrl: "https://www.zhipuai.cn",
    docsUrl: "https://open.bigmodel.cn/dev/api",
    icon: "zhipu",
    defaultBaseUrl: "https://open.bigmodel.cn/api/paas/v4",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "ZHIPU_API_KEY",
  },
  {
    id: "baichuan",
    name: "百川智能 (Baichuan)",
    type: "api-key",
    category: "api",
    description: "Baichuan models via official API key",
    websiteUrl: "https://www.baichuan-ai.com",
    docsUrl: "https://platform.baichuan-ai.com/docs",
    icon: "baichuan",
    defaultBaseUrl: "https://api.baichuan-ai.com/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "BAICHUAN_API_KEY",
  },
  {
    id: "moonshot",
    name: "月之暗面 (Moonshot)",
    type: "api-key",
    category: "api",
    description: "Kimi models via official API key",
    websiteUrl: "https://www.moonshot.cn",
    docsUrl: "https://platform.moonshot.cn/docs",
    icon: "kimi",
    defaultBaseUrl: "https://api.moonshot.cn/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "MOONSHOT_API_KEY",
  },
  {
    id: "01ai",
    name: "零一万物 (01.AI)",
    type: "api-key",
    category: "api",
    description: "Yi models via official API key",
    websiteUrl: "https://www.01.ai",
    docsUrl: "https://platform.01.ai/docs",
    icon: "zeroone",
    defaultBaseUrl: "https://api.01.ai/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "YI_API_KEY",
  },
  {
    id: "minimax",
    name: "MiniMax",
    type: "api-key",
    category: "api",
    description: "MiniMax models via official API key",
    websiteUrl: "https://www.minimaxi.com",
    docsUrl: "https://www.minimaxi.com/document/guides/chat-model/V2",
    icon: "minimax",
    defaultBaseUrl: "https://api.minimax.chat/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "MINIMAX_API_KEY",
  },
  {
    id: "doubao",
    name: "豆包 (Doubao)",
    type: "api-key",
    category: "api",
    description: "ByteDance models via official API key",
    websiteUrl: "https://www.volcengine.com/product/doubao",
    docsUrl: "https://www.volcengine.com/docs/82379",
    icon: "doubao",
    defaultBaseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "DOUBAO_API_KEY",
  },
  {
    id: "qwen",
    name: "通义千问 (Qwen)",
    type: "api-key",
    category: "api",
    description: "Alibaba Qwen models via official API key",
    websiteUrl: "https://tongyi.aliyun.com",
    docsUrl: "https://help.aliyun.com/zh/dashscope",
    icon: "qwen",
    defaultBaseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "DASHSCOPE_API_KEY",
  },
  {
    id: "hunyuan",
    name: "腾讯混元 (Hunyuan)",
    type: "api-key",
    category: "api",
    description: "Tencent Hunyuan models via official API key",
    websiteUrl: "https://hunyuan.tencent.com",
    docsUrl: "https://cloud.tencent.com/document/product/1729",
    icon: "hunyuan",
    defaultBaseUrl: "https://api.hunyuan.cloud.tencent.com/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "HUNYUAN_API_KEY",
  },
  {
    id: "stepfun",
    name: "阶跃星辰 (StepFun)",
    type: "api-key",
    category: "api",
    description: "Step models via official API key",
    websiteUrl: "https://www.stepfun.com",
    docsUrl: "https://platform.stepfun.com/docs",
    icon: "stepfun",
    defaultBaseUrl: "https://api.stepfun.com/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "STEPFUN_API_KEY",
  },
  // Cloud providers
  {
    id: "azure-openai",
    name: "Azure OpenAI",
    type: "api-key",
    category: "api",
    description: "OpenAI models via Azure",
    websiteUrl: "https://azure.microsoft.com/en-us/products/ai-services/openai-service",
    docsUrl: "https://learn.microsoft.com/en-us/azure/ai-services/openai",
    icon: "azure",
    defaultBaseUrl: "https://<resource-name>.openai.azure.com",
    defaultApi: "openai-responses",
    requiresApiKey: true,
    envKeyName: "AZURE_OPENAI_API_KEY",
  },
  {
    id: "aws-bedrock",
    name: "AWS Bedrock",
    type: "api-key",
    category: "api",
    description: "Foundation models via AWS Bedrock",
    websiteUrl: "https://aws.amazon.com/bedrock",
    docsUrl: "https://docs.aws.amazon.com/bedrock",
    icon: "aws",
    defaultBaseUrl: "https://bedrock-runtime.<region>.amazonaws.com",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "AWS_ACCESS_KEY_ID",
  },
  {
    id: "vertex-ai",
    name: "Vertex AI",
    type: "api-key",
    category: "api",
    description: "Google Cloud AI models",
    websiteUrl: "https://cloud.google.com/vertex-ai",
    docsUrl: "https://cloud.google.com/vertex-ai/docs",
    icon: "googlecloud",
    defaultBaseUrl: "https://<region>-aiplatform.googleapis.com",
    defaultApi: "google-generative-ai",
    requiresApiKey: true,
    envKeyName: "GOOGLE_APPLICATION_CREDENTIALS",
  },
  // Specialized providers
  {
    id: "groq",
    name: "Groq",
    type: "api-key",
    category: "api",
    description: "Ultra-fast inference with LPU",
    websiteUrl: "https://groq.com",
    docsUrl: "https://console.groq.com/docs",
    icon: "groq",
    defaultBaseUrl: "https://api.groq.com/openai/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "GROQ_API_KEY",
  },
  {
    id: "replicate",
    name: "Replicate",
    type: "api-key",
    category: "api",
    description: "Run open source models",
    websiteUrl: "https://replicate.com",
    docsUrl: "https://replicate.com/docs",
    icon: "replicate",
    defaultBaseUrl: "https://api.replicate.com/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "REPLICATE_API_TOKEN",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    type: "api-key",
    category: "api",
    description: "Inference API for open models",
    websiteUrl: "https://huggingface.co",
    docsUrl: "https://huggingface.co/docs/api-inference",
    icon: "huggingface",
    defaultBaseUrl: "https://api-inference.huggingface.co",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "HUGGINGFACE_API_KEY",
  },
  {
    id: "anyscale",
    name: "Anyscale",
    type: "api-key",
    category: "api",
    description: "Serverless endpoints for open models",
    websiteUrl: "https://www.anyscale.com",
    docsUrl: "https://docs.anyscale.com",
    icon: "anyscale",
    defaultBaseUrl: "https://api.endpoints.anyscale.com/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "ANYSCALE_API_KEY",
  },
  {
    id: "cerebras",
    name: "Cerebras",
    type: "api-key",
    category: "api",
    description: "World's fastest AI inference",
    websiteUrl: "https://cerebras.ai",
    docsUrl: "https://inference-docs.cerebras.ai",
    icon: "cerebras",
    defaultBaseUrl: "https://api.cerebras.ai/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "CEREBRAS_API_KEY",
  },
];

// ────────────────────────────────────────────────────────────────────────────
// GATEWAY (Aggregators & Relays) — 只保留可验证的真实服务与开源自托管项目
// ────────────────────────────────────────────────────────────────────────────

export const GATEWAY_PRESETS: OmpProviderPreset[] = [
  // Major aggregators
  {
    id: "openrouter",
    name: "OpenRouter",
    type: "gateway",
    category: "gateway",
    description: "Unified access to 200+ models",
    websiteUrl: "https://openrouter.ai",
    docsUrl: "https://openrouter.ai/docs",
    icon: "openrouter",
    defaultBaseUrl: "https://openrouter.ai/api/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "OPENROUTER_API_KEY",
  },
  {
    id: "siliconflow",
    name: "SiliconFlow",
    type: "gateway",
    category: "gateway",
    description: "中国领先的模型聚合平台",
    websiteUrl: "https://siliconflow.cn",
    docsUrl: "https://docs.siliconflow.cn",
    icon: "siliconflow",
    defaultBaseUrl: "https://api.siliconflow.cn/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "SILICONFLOW_API_KEY",
  },
  {
    id: "modelscope",
    name: "ModelScope",
    type: "gateway",
    category: "gateway",
    description: "阿里达摩院开源模型社区",
    websiteUrl: "https://www.modelscope.cn",
    docsUrl: "https://www.modelscope.cn/docs",
    icon: "modelscope",
    defaultBaseUrl: "https://api.modelscope.cn/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "MODELSCOPE_API_KEY",
  },
  // Open-source gateway projects (self-hosted)
  {
    id: "one-api",
    name: "One API",
    type: "gateway",
    category: "gateway",
    description: "开源聚合管理系统",
    websiteUrl: "https://github.com/songquanpeng/one-api",
    docsUrl: "https://github.com/songquanpeng/one-api/blob/main/README.md",
    icon: "one-api",
    defaultBaseUrl: "http://localhost:3000/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  {
    id: "new-api",
    name: "New API",
    type: "gateway",
    category: "gateway",
    description: "One API的增强分支",
    websiteUrl: "https://github.com/Calcium-Ion/new-api",
    icon: "newapi",
    defaultBaseUrl: "http://localhost:3000/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  {
    id: "fastgpt",
    name: "FastGPT",
    type: "gateway",
    category: "gateway",
    description: "知识库+聚合API平台",
    websiteUrl: "https://fastgpt.in",
    docsUrl: "https://doc.fastgpt.in",
    icon: "fastgpt",
    defaultBaseUrl: "https://api.fastgpt.in/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  // International aggregators
  {
    id: "novita",
    name: "Novita AI",
    type: "gateway",
    category: "gateway",
    description: "GPU cloud for AI inference",
    websiteUrl: "https://novita.ai",
    docsUrl: "https://novita.ai/docs",
    icon: "novita",
    defaultBaseUrl: "https://api.novita.ai/v3/openai",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  {
    id: "runpod",
    name: "RunPod",
    type: "gateway",
    category: "gateway",
    description: "GPU rental & serverless inference",
    websiteUrl: "https://www.runpod.io",
    docsUrl: "https://docs.runpod.io",
    icon: "runpod",
    defaultBaseUrl: "https://api.runpod.ai/v2",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  {
    id: "infermatic",
    name: "Infermatic",
    type: "gateway",
    category: "gateway",
    description: "Model serving platform",
    websiteUrl: "https://infermatic.ai",
    icon: "infermatic",
    defaultBaseUrl: "https://api.infermatic.ai/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  {
    id: "lepton",
    name: "Lepton AI",
    type: "gateway",
    category: "gateway",
    description: "AI platform with serverless GPUs",
    websiteUrl: "https://www.lepton.ai",
    docsUrl: "https://www.lepton.ai/docs",
    icon: "lepton",
    defaultBaseUrl: "https://api.lepton.ai/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  {
    id: "featherless",
    name: "Featherless AI",
    type: "gateway",
    category: "gateway",
    description: "Cheap inference for open models",
    websiteUrl: "https://featherless.ai",
    icon: "featherless",
    defaultBaseUrl: "https://api.featherless.ai/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  {
    id: "together-xyz",
    name: "Together (XYZ)",
    type: "gateway",
    category: "gateway",
    description: "Fast open model inference",
    websiteUrl: "https://api.together.xyz",
    icon: "together",
    defaultBaseUrl: "https://api.together.xyz/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  {
    id: "deepinfra",
    name: "DeepInfra",
    type: "gateway",
    category: "gateway",
    description: "Scalable AI inference",
    websiteUrl: "https://deepinfra.com",
    docsUrl: "https://deepinfra.com/docs",
    icon: "deepinfra",
    defaultBaseUrl: "https://api.deepinfra.com/v1/openai",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  {
    id: "octo",
    name: "Octo AI",
    type: "gateway",
    category: "gateway",
    description: "Optimized inference endpoints",
    websiteUrl: "https://octo.ai",
    docsUrl: "https://docs.octo.ai",
    icon: "octo",
    defaultBaseUrl: "https://api.octoai.cloud/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  {
    id: "unify",
    name: "Unify AI",
    type: "gateway",
    category: "gateway",
    description: "Router for all LLM providers",
    websiteUrl: "https://unify.ai",
    docsUrl: "https://docs.unify.ai",
    icon: "unify",
    defaultBaseUrl: "https://api.unify.ai/v0",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  {
    id: "portkey",
    name: "Portkey",
    type: "gateway",
    category: "gateway",
    description: "LLM gateway with observability",
    websiteUrl: "https://portkey.ai",
    docsUrl: "https://docs.portkey.ai",
    icon: "portkey",
    defaultBaseUrl: "https://api.portkey.ai/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  {
    id: "helicone",
    name: "Helicone",
    type: "gateway",
    category: "gateway",
    description: "LLM observability platform",
    websiteUrl: "https://www.helicone.ai",
    docsUrl: "https://docs.helicone.ai",
    icon: "helicone",
    defaultBaseUrl: "https://oai.helicone.ai/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  {
    id: "langfuse",
    name: "Langfuse",
    type: "gateway",
    category: "gateway",
    description: "Open source LLM engineering platform",
    websiteUrl: "https://langfuse.com",
    docsUrl: "https://langfuse.com/docs",
    icon: "langfuse",
    defaultBaseUrl: "https://cloud.langfuse.com/api",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  {
    id: "litellm",
    name: "LiteLLM Proxy",
    type: "gateway",
    category: "gateway",
    description: "Local proxy for 100+ LLM APIs",
    websiteUrl: "https://github.com/BerriAI/litellm",
    docsUrl: "https://docs.litellm.ai",
    icon: "litellm",
    defaultBaseUrl: "http://localhost:4000",
    defaultApi: "openai-completions",
    requiresApiKey: false,
  },
  {
    id: "nebius",
    name: "Nebius AI",
    type: "gateway",
    category: "gateway",
    description: "European AI cloud",
    websiteUrl: "https://nebius.ai",
    docsUrl: "https://docs.nebius.ai",
    icon: "nebius",
    defaultBaseUrl: "https://api.nebius.ai/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  {
    id: "lambda",
    name: "Lambda Labs",
    type: "gateway",
    category: "gateway",
    description: "GPU cloud for AI training & inference",
    websiteUrl: "https://lambdalabs.com",
    docsUrl: "https://docs.lambdalabs.com",
    icon: "lambda",
    defaultBaseUrl: "https://api.lambdalabs.com/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  {
    id: "modal",
    name: "Modal",
    type: "gateway",
    category: "gateway",
    description: "Serverless GPU infrastructure",
    websiteUrl: "https://modal.com",
    docsUrl: "https://modal.com/docs",
    icon: "modal",
    defaultBaseUrl: "https://api.modal.com/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
  },
  // ── 第十一轮补全：omp 官方 providers.md 内置支持的 API 型供应商 ──
  // baseUrl 来自本机 ~/.omp/agent/models.db 实证；缺实证者留空（表单可填）不猜。
  {
    id: "nanogpt",
    name: "NanoGPT",
    type: "gateway",
    category: "gateway",
    description: "NanoGPT API",
    icon: "nanogpt",
    websiteUrl: "https://nano-gpt.com",
    defaultBaseUrl: "https://nano-gpt.com/api/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "NANO_GPT_API_KEY",
  },
  {
    id: "meta",
    name: "Meta (Llama)",
    type: "gateway",
    category: "gateway",
    description: "Meta Llama models via API",
    websiteUrl: "https://ai.meta.com",
    icon: "meta",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "META_API_KEY",
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    type: "gateway",
    category: "gateway",
    description: "NVIDIA NIM hosted models",
    websiteUrl: "https://build.nvidia.com",
    docsUrl: "https://docs.api.nvidia.com",
    icon: "nvidia",
    defaultBaseUrl: "https://integrate.api.nvidia.com/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "NVIDIA_API_KEY",
  },
  {
    id: "venice",
    name: "Venice AI",
    type: "gateway",
    category: "gateway",
    description: "Venice AI priva-free inference",
    icon: "venice",
    websiteUrl: "https://venice.ai",
    defaultBaseUrl: "https://api.venice.ai/api/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "VENICE_API_KEY",
  },
  {
    id: "zenmux",
    name: "ZenMux",
    type: "gateway",
    category: "gateway",
    description: "ZenMux AI gateway (Anthropic-compatible)",
    icon: "zenmux",
    websiteUrl: "https://zenmux.ai",
    defaultBaseUrl: "https://zenmux.ai/api/anthropic",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "ZENMUX_API_KEY",
  },
  {
    id: "kilo",
    name: "Kilo Code",
    type: "gateway",
    category: "gateway",
    description: "Kilo Code gateway",
    icon: "kilocode",
    websiteUrl: "https://kilo.ai",
    defaultBaseUrl: "https://api.kilo.ai/api/gateway",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "KILO_API_KEY",
  },
  {
    id: "umans",
    name: "UMANS AI",
    type: "gateway",
    category: "gateway",
    description: "UMANS AI coding plan",
    icon: "umans",
    websiteUrl: "https://umans.ai",
    requiresApiKey: true,
    envKeyName: "UMANS_AI_CODING_PLAN_API_KEY",
  },
  {
    id: "synthetic",
    name: "Synthetic",
    type: "gateway",
    category: "gateway",
    description: "Synthetic AI",
    icon: "synthetic",
    websiteUrl: "https://synthetic.com",
    requiresApiKey: true,
    envKeyName: "SYNTHETIC_API_KEY",
  },
  {
    id: "aimlapi",
    name: "AIMLAPI",
    type: "gateway",
    category: "gateway",
    description: "AIMLAPI multi-model gateway",
    icon: "aimlapi",
    websiteUrl: "https://aimlapi.com",
    docsUrl: "https://docs.aimlapi.com",
    requiresApiKey: true,
    envKeyName: "AIMLAPI_API_KEY",
  },
  {
    id: "charm-hyper",
    name: "Charm Hyper",
    type: "gateway",
    category: "gateway",
    description: "Charm OpenAI-compatible inference gateway",
    icon: "charm",
    websiteUrl: "https://hyper.charm.land",
    defaultBaseUrl: "https://hyper.charm.land/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "CHARM_HYPER_API_KEY",
  },
  {
    id: "coreweave",
    name: "CoreWeave",
    type: "gateway",
    category: "gateway",
    description: "CoreWeave hosted models",
    icon: "coreweave",
    websiteUrl: "https://coreweave.com",
    docsUrl: "https://docs.coreweave.com",
    requiresApiKey: true,
    envKeyName: "COREWEAVE_API_KEY",
  },
  {
    id: "baseten",
    name: "Baseten",
    type: "gateway",
    category: "gateway",
    description: "Baseten model serving",
    icon: "baseten",
    websiteUrl: "https://baseten.co",
    docsUrl: "https://docs.baseten.co",
    requiresApiKey: true,
    envKeyName: "BASETEN_API_KEY",
  },
  {
    id: "gmi-cloud",
    name: "GMI Cloud",
    type: "gateway",
    category: "gateway",
    description: "GMI Cloud",
    icon: "gmi-cloud",
    websiteUrl: "https://gmicloud.com",
    requiresApiKey: true,
    envKeyName: "GMI_API_KEY",
  },
  {
    id: "aiand",
    name: "AI&",
    type: "gateway",
    category: "gateway",
    description: "AI& models",
    icon: "aiand",
    websiteUrl: "https://aiand.ai",
    requiresApiKey: true,
    envKeyName: "AIAND_API_KEY",
  },
  {
    id: "vercel-ai-gateway",
    name: "Vercel AI Gateway",
    type: "gateway",
    category: "gateway",
    description: "Vercel AI Gateway",
    websiteUrl: "https://vercel.com/docs/ai",
    icon: "vercel",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "AI_GATEWAY_API_KEY",
  },
  {
    id: "cloudflare-ai-gateway",
    name: "Cloudflare AI Gateway",
    type: "gateway",
    category: "gateway",
    description: "Cloudflare AI Gateway（需 account/gateway id + token）",
    websiteUrl: "https://developers.cloudflare.com/ai-gateway",
    icon: "cloudflare",
    defaultBaseUrl: "https://gateway.ai.cloudflare.com/v1/<account>/<gateway>/anthropic",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "CLOUDFLARE_AI_GATEWAY_API_KEY",
  },
  {
    id: "siliconflow-cn",
    name: "SiliconFlow CN",
    type: "gateway",
    category: "gateway",
    description: "硅基流动（国内版）",
    websiteUrl: "https://cloud.siliconflow.cn",
    icon: "siliconflow",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "SILICONFLOW_CN_API_KEY",
  },
  {
    id: "xiaomi",
    name: "Xiaomi MiMo",
    type: "gateway",
    category: "gateway",
    description: "Xiaomi MiMo API",
    websiteUrl: "https://www.xiaomimimo.com",
    icon: "xiaomimimo",
    defaultBaseUrl: "https://api.xiaomimimo.com/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "XIAOMI_API_KEY",
  },
  {
    id: "xiaomi-token-plan-ams",
    name: "Xiaomi MiMo Plan (AMS)",
    type: "gateway",
    category: "gateway",
    description: "Xiaomi MiMo Token Plan 美洲节点",
    websiteUrl: "https://www.xiaomimimo.com",
    icon: "xiaomimimo",
    defaultBaseUrl: "https://token-plan-ams.xiaomimimo.com/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "XIAOMI_TOKEN_PLAN_AMS_API_KEY",
  },
  {
    id: "xiaomi-token-plan-cn",
    name: "Xiaomi MiMo Plan (CN)",
    type: "gateway",
    category: "gateway",
    description: "Xiaomi MiMo Token Plan 国内节点",
    websiteUrl: "https://www.xiaomimimo.com",
    icon: "xiaomimimo",
    defaultBaseUrl: "https://token-plan-cn.xiaomimimo.com/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "XIAOMI_TOKEN_PLAN_CN_API_KEY",
  },
  {
    id: "xiaomi-token-plan-sgp",
    name: "Xiaomi MiMo Plan (SGP)",
    type: "gateway",
    category: "gateway",
    description: "Xiaomi MiMo Token Plan 新加坡节点",
    websiteUrl: "https://www.xiaomimimo.com",
    icon: "xiaomimimo",
    defaultBaseUrl: "https://token-plan-sgp.xiaomimimo.com/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "XIAOMI_TOKEN_PLAN_SGP_API_KEY",
  },
  {
    id: "alibaba-coding-plan",
    name: "Alibaba Coding Plan",
    type: "gateway",
    category: "gateway",
    description: "Alibaba Coding Plan（国际版通义）",
    websiteUrl: "https://coding.dashscope.com",
    icon: "alibaba",
    defaultBaseUrl: "https://coding-intl.dashscope.aliyuncs.com/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "ALIBABA_CODING_PLAN_API_KEY",
  },
  {
    id: "alibaba-token-plan",
    name: "Alibaba Token Plan",
    type: "gateway",
    category: "gateway",
    description: "Alibaba Bailian Token Plan",
    websiteUrl: "https://www.alibabacloud.com/help/model-studio",
    icon: "bailian",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "ALIBABA_TOKEN_PLAN_API_KEY",
  },
  {
    id: "minimax-code",
    name: "MiniMax Code",
    type: "gateway",
    category: "gateway",
    description: "MiniMax Code（海外）",
    websiteUrl: "https://minimax.io",
    icon: "minimax",
    defaultBaseUrl: "https://api.minimax.io/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "MINIMAX_CODE_API_KEY",
  },
  {
    id: "minimax-code-cn",
    name: "MiniMax Code (CN)",
    type: "gateway",
    category: "gateway",
    description: "MiniMax Code（国内）",
    websiteUrl: "https://minimaxi.com",
    icon: "minimax",
    defaultBaseUrl: "https://api.minimaxi.com/v1",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "MINIMAX_CODE_CN_API_KEY",
  },
  {
    id: "qianfan",
    name: "百度千帆",
    type: "gateway",
    category: "gateway",
    description: "百度智能云千帆",
    websiteUrl: "https://qianfan.cloud.baidu.com",
    icon: "baidu",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "QIANFAN_API_KEY",
  },
  {
    id: "opencode-zen",
    name: "OpenCode Zen",
    type: "gateway",
    category: "gateway",
    description: "OpenCode Zen",
    websiteUrl: "https://opencode.ai",
    icon: "opencode",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "OPENCODE_API_KEY",
  },
  {
    id: "opencode-go",
    name: "OpenCode Go",
    type: "gateway",
    category: "gateway",
    description: "OpenCode Go",
    websiteUrl: "https://opencode.ai",
    icon: "opencode",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "OPENCODE_API_KEY",
  },
  {
    id: "cline-pass",
    name: "ClinePass",
    type: "gateway",
    category: "gateway",
    description: "Cline Dashboard API key",
    icon: "cline",
    websiteUrl: "https://cline.bot",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "CLINE_API_KEY",
  },
  {
    id: "firepass",
    name: "FirePass",
    type: "gateway",
    category: "gateway",
    description: "FirePass",
    icon: "fireworks",
    websiteUrl: "https://firepass.io",
    requiresApiKey: true,
    envKeyName: "FIREPASS_API_KEY",
  },
  {
    id: "yolo-auto",
    name: "YOLO Auto",
    type: "gateway",
    category: "gateway",
    description: "YOLO Auto",
    icon: "yolo-auto",
    websiteUrl: "https://yolo.ai",
    requiresApiKey: true,
    envKeyName: "YOLO_AUTO_API_KEY",
  },
  {
    id: "sakana",
    name: "Sakana AI",
    type: "gateway",
    category: "gateway",
    description: "Sakana AI（Fugu 模型）",
    icon: "sakana",
    websiteUrl: "https://sakana.ai",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "SAKANA_API_KEY",
  },
  {
    id: "bedrock-mantle",
    name: "Bedrock Mantle",
    type: "gateway",
    category: "gateway",
    description: "Bedrock Mantle (AWS bearer token)",
    websiteUrl: "https://aws.amazon.com/bedrock",
    icon: "aws",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "AWS_BEARER_TOKEN_BEDROCK",
  },
  // ── 以下 5 个原误置于 OAuth 组：omp 源码 kdl 的 login="api-key" ──
  // （baseUrl 无实证，留空由表单填写）
  {
    id: "ollama-cloud",
    name: "Ollama Cloud",
    type: "api-key",
    category: "gateway",
    description: "Ollama 云端模型（API Key）",
    websiteUrl: "https://ollama.com",
    docsUrl: "https://docs.ollama.com",
    icon: "ollama",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "OLLAMA_CLOUD_API_KEY",
  },
  {
    id: "qwen-portal",
    name: "Qwen Portal",
    type: "api-key",
    category: "gateway",
    description: "Qwen Portal（API Key）",
    websiteUrl: "https://chat.qwen.ai",
    icon: "qwen",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "QWEN_PORTAL_API_KEY",
  },
  {
    id: "wafer-serverless",
    name: "Wafer Serverless",
    type: "api-key",
    category: "gateway",
    description: "Wafer Serverless（API Key，按量付费）",
    websiteUrl: "https://www.wafer.dev",
    icon: "wafer",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "WAFER_SERVERLESS_API_KEY",
  },
  {
    id: "zai",
    name: "Z.AI（GLM Coding Plan）",
    type: "api-key",
    category: "gateway",
    description: "Z.AI GLM Coding Plan 全局端点（API Key）",
    websiteUrl: "https://z.ai",
    icon: "zhipu",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "ZAI_API_KEY",
  },
  {
    id: "zhipu-coding-plan",
    name: "智谱 Coding Plan",
    type: "api-key",
    category: "gateway",
    description: "智谱国内 Coding Plan（API Key）",
    websiteUrl: "https://bigmodel.cn",
    icon: "zhipu",
    defaultApi: "openai-completions",
    requiresApiKey: true,
    envKeyName: "ZHIPU_API_KEY",
  },
];

// ────────────────────────────────────────────────────────────────────────────
// LOCAL (Self-hosted) - 5 providers
// ────────────────────────────────────────────────────────────────────────────

export const LOCAL_PRESETS: OmpProviderPreset[] = [
  {
    id: "ollama",
    name: "Ollama",
    type: "local",
    category: "local",
    description: "Run LLMs locally with Ollama",
    websiteUrl: "https://ollama.com",
    docsUrl: "https://github.com/ollama/ollama",
    icon: "ollama",
    defaultBaseUrl: "http://localhost:11434/v1",
    defaultApi: "openai-completions",
    requiresApiKey: false,
  },
  {
    id: "lm-studio",
    name: "LM Studio",
    type: "local",
    category: "local",
    description: "Desktop app for local LLMs",
    websiteUrl: "https://lmstudio.ai",
    icon: "lm-studio",
    defaultBaseUrl: "http://localhost:1234/v1",
    defaultApi: "openai-completions",
    requiresApiKey: false,
  },
  {
    id: "text-generation-webui",
    name: "Text Generation WebUI",
    type: "local",
    category: "local",
    description: "Oobabooga's local inference server",
    websiteUrl: "https://github.com/oobabooga/text-generation-webui",
    icon: "text-generation-webui",
    defaultBaseUrl: "http://localhost:5000/v1",
    defaultApi: "openai-completions",
    requiresApiKey: false,
  },
  {
    id: "vllm",
    name: "vLLM",
    type: "local",
    category: "local",
    description: "High-throughput local inference",
    websiteUrl: "https://vllm.ai",
    docsUrl: "https://docs.vllm.ai",
    icon: "vllm",
    defaultBaseUrl: "http://localhost:8000/v1",
    defaultApi: "openai-completions",
    requiresApiKey: false,
  },
  {
    id: "llamacpp",
    name: "llama.cpp",
    type: "local",
    category: "local",
    description: "C++ LLM inference engine",
    websiteUrl: "https://github.com/ggerganov/llama.cpp",
    icon: "llamacpp",
    defaultBaseUrl: "http://localhost:8080/v1",
    defaultApi: "openai-completions",
    requiresApiKey: false,
  },
];

// ────────────────────────────────────────────────────────────────────────────
// Exports & Utils
// ────────────────────────────────────────────────────────────────────────────

/**
 * All OMP presets
 */
export const ALL_OMP_PRESETS: OmpProviderPreset[] = [
  ...SUBSCRIPTION_PRESETS,  // OAuth
  ...API_PRESETS,           // API Key
  ...GATEWAY_PRESETS,       // API Key
  ...LOCAL_PRESETS,         // API Key
];

/**
 * Find preset by ID
 */
export function findPresetById(id: string): OmpProviderPreset | undefined {
  return ALL_OMP_PRESETS.find((preset) => preset.id === id);
}

/**
 * Get presets by category
 */
export function getPresetsByCategory(
  category: OmpProviderPreset["category"],
): OmpProviderPreset[] {
  return ALL_OMP_PRESETS.filter((preset) => preset.category === category);
}

/**
 * Get presets by type
 */
export function getPresetsByType(
  type: OmpProviderPreset["type"],
): OmpProviderPreset[] {
  return ALL_OMP_PRESETS.filter((preset) => preset.type === type);
}

/**
 * Search presets by name or description
 */
export function searchPresets(query: string): OmpProviderPreset[] {
  const lowerQuery = query.toLowerCase();
  return ALL_OMP_PRESETS.filter(
    (preset) =>
      preset.name.toLowerCase().includes(lowerQuery) ||
      preset.description.toLowerCase().includes(lowerQuery) ||
      preset.id.toLowerCase().includes(lowerQuery),
  );
}
